# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linux:
    name: Start container
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Minify Action
        uses: anthonyftwang/minify-action@v1.0.1
        
      - name: Spin up Container
        run: docker-compose up -d --build

      

